// <auto-generated />
using EmployeeMangment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeMangment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250302200945_AddEmployeeSeedData")]
    partial class AddEmployeeSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("EmployeeMangment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe",
                            Position = "Manager",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith",
                            Position = "Developer",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alice Johnson",
                            Position = "Designer",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bob Brown",
                            Position = "Tester",
                            Salary = 40000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Charlie Davis",
                            Position = "Developer",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = 6,
                            Name = "David Lee",
                            Position = "Manager",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Eva Clark",
                            Position = "Developer",
                            Salary = 48000m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Frank Moore",
                            Position = "Sales",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Grace Taylor",
                            Position = "HR",
                            Salary = 46000m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Helen Harris",
                            Position = "Support",
                            Salary = 42000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
